# Generated by Django 3.0.7 on 2020-08-01 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('patronymic', models.CharField(max_length=64, null=True)),
                ('phone_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('delivered', 'Delivered'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='created', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deliver_at', models.DateTimeField()),
                ('delivery_address', models.CharField(max_length=512)),
                ('product_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapter_two.ProductSet')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chapter_two.Recipient')),
            ],
        ),
    ]
